name: Build & Deploy ke main

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy ke main
        run: |
          cd frontend/dist
          git init
          git add .
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -m "Deploy frontend ke main"
          git branch -M main
          git remote add origin https://github.com/MoonVibes0012/fishgpt.git
          git push -f origin main
